version: "3.9"
services:
  django:
    build:
      context: ../../
      dockerfile: deploy/app/django.Dockerfile
    command: ./deploy/app/run.sh
    ports:
      - "8000:8000"
  nginx:
    build: deploy/app/nginx.Dockerfile
    build:
      context: ../../
      dockerfile: deploy/app/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django
